### ISSUE TITLE
For_each vpc_id depends on apply first

### ISSUE THREAD

**Issue by rastakajakwanna** [ugns/terraform-aws-route53-dnssec#2]
Hello,

please consider removing or changing the for_each on random and aws_route53_key_signing_key resources as the for_each expects existing values and therefore this module cannot have dynamic dependencies.

If you leave it, the for_each variable shall be known values (perhaps domain names?).

If you remove it, for_each could be implemented by integrators on module level.

Current state does not allow to chain this module for example with outputs from this module: https://github.com/terraform-aws-modules/terraform-aws-route53 , because zone_id is known after apply.

Thank you

**Comment by jbouse** [comment]
Can you provide an example of the use case you're seeing that won't work? I admit this could probably use some redesign as it admittedly was purpose-built for my setup but I would welcome making it much more generic and reusable. 

The problem case that I was attempting to solve was that I was using the same KMS key for several hosted zones that were grouped together but wanted a unique KSK name in Route53 for each zone even though the KMS key was the same. So in my use case, I'm passing the `terraform-aws-route53-dnssec` module the list of hosted zone IDs from a private repo. I'm not currently using the `terraform-aws-route53` or any other registry module to create the zones themselves. In fact I have another private module that collects the hosted zone IDs from the state files of the zone files. Again admittedly a pattern I probably should revisit and improve but haven't had time and it is currently working but it is 2022 so I should perform some key rotation.

**Comment by rastakajakwanna** [comment]
Here it is:
```
locals {
  r53_domain_name            = "example.com"
  r53_domain_main_id         = module.route53-zones.route53_zone_zone_id[local.r53_domain_name]
}

module "route53-zones" {
  source  = "terraform-aws-modules/route53/aws//modules/zones"
  version = "~> 2.0"

  zones = {
    "${local.r53_domain_name}" = {
      comment = local.r53_domain_name
    }
  }
}

module "route53-dnssec-ksk" {
  source  = "UGNS/route53-dnssec/aws"
  version = "0.1.0"

  zone_ids = [
    local.r53_domain_main_id,
  ]
}
```
If the domain "example.com" does not exist, then the value is known only after apply and Terraform plan errors stating that.
You can find that information in the [Terraform for_each meta-argument documentation](https://www.terraform.io/language/meta-arguments/for_each#limitations-on-values-used-in-for_each).

I've forked your module and refactored that meta-argument dependency a little bit, so that it expects the following input:
```
module "route53-dnssec" {
  source  = "app.terraform.io/XXX/route53-dnssec/aws"
  version = "1.0.1"

  zones = {
    "${local.r53_domain_name}" = {
      zone_id = local.r53_domain_main_id
    }
  }
}
```
For_each can loop over maps too, the map key still must be known value (in order to allow Terraform see the array size), but map helps to pass those variables we need.

It looks like this in the module:
```
variable "zones" {
  description = "Hosted Zone IDs to assign KSK to"
  type        = map(map(string))
  default     = {}
}

resource "random_string" "ksk" {
  for_each = var.zones

  keepers = {
    hosted_zone_id             = each.value.zone_id
    key_management_service_arn = aws_kms_key.this.arn
  }

  length  = 32
  special = false
}

resource "aws_route53_key_signing_key" "this" {
  for_each = var.zones

  hosted_zone_id             = random_string.ksk[each.key].keepers.hosted_zone_id
  key_management_service_arn = aws_kms_key.this.arn
  name                       = random_string.ksk[each.key].id
}
```
I am not saying it is the best possible way to do it, but I had to fix it fast 😄 I've made similar "mistakes" too (and keep doing them), but after facing this several times, I'm getting better in avoiding it 😄

How to correctly chain for_each loops is also perfectly described directly [in the for_each meta-argument documentation](https://www.terraform.io/language/meta-arguments/for_each#chaining-for_each-between-resources).

I understand your reasons very well (we are all professionally basically on the same boat) but I very much appreciate your work you did by publishing the module to the community and I am glad that I could help to improve it.

**Comment by jbouse** [comment]
Okay, now I think I'm following you more... It wasn't the `random_string` resource itself but the structure of the variables that caused the problem. I can probably chalk that up to the oversight that I wrote the module after some manual testing and didn't test cleanly from scratch.

Thank you for catching this and letting me know. I had planned to be doing some refactoring work so I'll include this in the effort as I'm sure I would have likely come across this as part of the effort is moving my AWS account into a multi-account organization which would have meant setting up new zones from scratch. I'm also hoping to work in some more validation testing as well, if you're up for it would welcome the collaboration.

**Comment by rastakajakwanna** [comment]
You are welcome and good luck with the refactoring.

Regarding the collaboration, thank you for the offer, I appreciate it, but my free time allows only occasional bug reporting, unfortunately. Anyway, I will be emailed when you update this issue, so if time allows, I will try to help.

**Comment by jbouse** [comment]
I believe I have this working in a compatible fashion now, but it is ultimately going to be a breaking change release despite my best efforts to work around that and attempt some form of a migration path.

Running a `terraform plan` against my test data I get the following:
```
Initializing Terraform configuration...

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.ksk.aws_route53_key_signing_key.this["example.com"] will be created
  + resource "aws_route53_key_signing_key" "this" {
      + digest_algorithm_mnemonic  = (known after apply)
      + digest_algorithm_type      = (known after apply)
      + digest_value               = (known after apply)
      + dnskey_record              = (known after apply)
      + ds_record                  = (known after apply)
      + flag                       = (known after apply)
      + hosted_zone_id             = (known after apply)
      + id                         = (known after apply)
      + key_management_service_arn = (known after apply)
      + key_tag                    = (known after apply)
      + name                       = (known after apply)
      + public_key                 = (known after apply)
      + signing_algorithm_mnemonic = (known after apply)
      + signing_algorithm_type     = (known after apply)
      + status                     = "ACTIVE"
    }

  # module.ksk.random_string.ksk["example.com"] will be created
  + resource "random_string" "ksk" {
      + id          = (known after apply)
      + keepers     = (known after apply)
      + length      = 32
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + result      = (known after apply)
      + special     = false
      + upper       = true
    }

  # module.ksk.module.kms_key.aws_kms_alias.default[0] will be created
  + resource "aws_kms_alias" "default" {
      + arn            = (known after apply)
      + id             = (known after apply)
      + name           = "alias/kms-key-test"
      + name_prefix    = (known after apply)
      + target_key_arn = (known after apply)
      + target_key_id  = (known after apply)
    }

  # module.ksk.module.kms_key.aws_kms_key.default[0] will be created
  + resource "aws_kms_key" "default" {
      + arn                                = (known after apply)
      + bypass_policy_lockout_safety_check = false
      + customer_master_key_spec           = "ECC_NIST_P256"
      + deletion_window_in_days            = 7
      + description                        = "Route53 DNSSEC customer managed CMK"
      + enable_key_rotation                = false
      + id                                 = (known after apply)
      + is_enabled                         = true
      + key_id                             = (known after apply)
      + key_usage                          = "SIGN_VERIFY"
      + multi_region                       = false
      + policy                             = jsonencode(
            {
              + Id        = "dnssec-policy"
              + Statement = [
                  + {
                      + Action    = "kms:*"
                      + Effect    = "Allow"
                      + Principal = {
                          + AWS = "arn:aws:iam::123456789012:root"
                        }
                      + Resource  = "*"
                      + Sid       = "Enable IAM User Permissions"
                    },
                  + {
                      + Action    = [
                          + "kms:Sign",
                          + "kms:GetPublicKey",
                          + "kms:DescribeKey",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "dnssec-route53.amazonaws.com"
                        }
                      + Resource  = "*"
                      + Sid       = "Allow Route 53 DNSSEC Service"
                    },
                  + {
                      + Action    = "kms:CreateGrant"
                      + Condition = {
                          + Bool = {
                              + kms:GrantIsForAWSResource = "true"
                            }
                        }
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "dnssec-route53.amazonaws.com"
                        }
                      + Resource  = "*"
                      + Sid       = "Allow Route 53 DNSSEC to CreateGrant"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + tags                               = {
          + "Name" = "kms-key-test"
        }
      + tags_all                           = {
          + "Name" = "kms-key-test"
        }
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + this_key_arn = (known after apply)
```

This is executing it as follows:
```
module "ksk" {
  source = "github.com/ugns/terraform-aws-route53-dnssec?ref=devel"

  name    = "kms-key-test"
  zones   = {
    "example.com" = {
      zone_id = "12345678"
    }
  }
}
```

If you want to give this a test run yourself and validate that would be great. I'll then plan to release it as `1.0.0` with clear notice added to the `README.md` about breaking changes from versions `< 1.0.0`. As you'll note the `name` variable is required at a minimum or any other context variables for [cloudposse/label/null](https://github.com/cloudposse/terraform-null-label).
