### ISSUE TITLE
Remove module specific tags

### ISSUE THREAD

**Issue by rastakajakwanna** [ugns/terraform-aws-route53-dnssec#3]
Hello,

please consider removing the module specific tags. There are multiple reasons to do that:
- integrators might be limited by tag keys allowed by corporate naming convention (my case)
- when used with tf provider-level default tags, it may cause constant drift (my case)
- integrators might simply wish to use their own tags and not seeing them merged with some default module tags

Thank you

**Comment by jbouse** [comment]
Thank you for this... I was actually looking at removing them as I'd been dealing with the same drift myself. This was from early module development and a lesson learned. I'll be cutting a new `devel` branch and moving to context pattern that can provide consistency but should not produce the drift issue and is easily overridden by any customizations.
